apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-cls-admin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-cls-admin
  labels:
    k8s-app: k8s-cls-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: k8s-cls-admin
  namespace: kube-system
